# Generated by Django 4.2.5 on 2023-10-03 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='las_name',
            new_name='last_name',
        ),
    ]
